import type { DreamStory } from '../components/DreamStoryList.vue';
export declare const dreamStories: import("vue").Ref<{
    id: string;
    title: string;
    description: string;
    coverImage: string;
    isNew: boolean;
    isLocked?: boolean | undefined;
    progress: number;
    totalChapters?: number | undefined;
    completedChapters?: number | undefined;
    comingSoon?: boolean | undefined;
}[], DreamStory[] | {
    id: string;
    title: string;
    description: string;
    coverImage: string;
    isNew: boolean;
    isLocked?: boolean | undefined;
    progress: number;
    totalChapters?: number | undefined;
    completedChapters?: number | undefined;
    comingSoon?: boolean | undefined;
}[]>;
export declare function getAllStories(): import("vue").Ref<{
    id: string;
    title: string;
    description: string;
    coverImage: string;
    isNew: boolean;
    isLocked?: boolean | undefined;
    progress: number;
    totalChapters?: number | undefined;
    completedChapters?: number | undefined;
    comingSoon?: boolean | undefined;
}[], DreamStory[] | {
    id: string;
    title: string;
    description: string;
    coverImage: string;
    isNew: boolean;
    isLocked?: boolean | undefined;
    progress: number;
    totalChapters?: number | undefined;
    completedChapters?: number | undefined;
    comingSoon?: boolean | undefined;
}[]>;
export declare function getStoryById(id: string): DreamStory | undefined;
export declare function updateStoryProgress(id: string, progress: number): boolean;
export declare function getUnlockedStories(): DreamStory[];
export declare function showLockedMessage(story: DreamStory): void;
