import type { Character } from '../types/character';
export declare const characterQiangQingCiB001C001: Character;
export declare const characterChengYuhuaiB001C002: Character;
export declare const characterChengYuhuaiB001C003: Character;
export declare const characterChengZouliuB001C004: Character;
export declare const characterDelilahB001C005: Character;
export declare const characterArchieB001C009: Character;
export declare const characterJiangBojiaB001C006: Character;
export declare const characterMiaoHongmoB001C007: Character;
export declare const characterIsaacB001C008: Character;
export declare const characterBuLuoJiB002C001: Character;
export declare const characterXiaoGuanB002C002: Character;
export declare const characterXuBaB002C003: Character;
export declare const characterYangYangB002C004: Character;
export declare const characterYongXuB002C005: Character;
export declare const characterZiShuB002C006: Character;
export declare const characters: Character[];
export declare const getDefaultCharacter: () => Character;
export declare const getCharacterById: (id: string) => Character | undefined;
